# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          moreTale
paginate:       5
baseurl:        "/moretale"
url:            "https://lsrom.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Luke Srom
  url:          http://lsrom.cz
  email:        lukas.srom@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/lsrom/moreTale

# Gems
plugins:
  - jekyll-paginate
